In [6]:
import pandas as pd
import numpy as np

Reading file with pandas

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [8]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Checking version of pandas

In [9]:
pd.__version__

'2.3.1'

How many records are in the dataset?

In [104]:
len(df)

9704

How many fuel types are presented in the dataset?

In [10]:
df['fuel_type'].nunique()

2

How many columns in the dataset have missing values?

In [28]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

What's the maximum fuel efficiency of cars from Asia?

In [35]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

Median value of horsepower

1. Find the median value of horsepower column in the dataset.

In [39]:
df['horsepower'].median()

np.float64(149.0)

2. Next, calculate the most frequent value of the same horsepower column.

In [44]:
df["horsepower"].mode()[0]

np.float64(152.0)

3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

In [50]:
df["horsepower"].fillna(152.0, inplace=True)

4. Now, calculate the median value of horsepower once again.

In [51]:
df['horsepower'].median()

np.float64(152.0)

Sum of weights

1. Select all the cars from Asia

In [54]:
df[
    df['origin'] == 'Asia'
]

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [62]:
df.loc[
    df['origin'] == 'Asia',
    ['vehicle_weight','model_year']
]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

3. Select the first 7 values

In [12]:
df.loc[
    df['origin'] == 'Asia',
    ['vehicle_weight','model_year'],
    
].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

4. Get the underlying NumPy array. Let's call it X

In [13]:
df_to_x = df.loc[
    df['origin'] == 'Asia',
    ['vehicle_weight','model_year'],
    
].head(7)

X = df_to_x.to_numpy()

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX

In [14]:
def vector_vector_multiplication(v1, v2):
    assert len(v1) == len(v2)
    result = 0.0
    for i in range(len(v1)):
        result += v1[i] * v2[i]
    return result


def matrix_vector_multiplication(M, v):
    num_rows = M.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(M[i, :], v)
    return result

def matrix_matrix_multiplication(X):
    X_T = X.T
    num_rows, num_cols = X_T.shape[0], X.shape[1]  
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_rows):
        for j in range(num_cols):
            result[i, j] = vector_vector_multiplication(X_T[i, :], X[:, j])
    return result


XTX = matrix_matrix_multiplication(X)

In [15]:
matrix_matrix_multiplication(X)

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

6. Invert XTX.

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [18]:
X_T = X.T

w = XTX_inv @ X_T @ y


In [19]:
w

array([0.01386421, 0.5049067 ])

In [20]:
np.sum(w)

np.float64(0.5187709081074003)