In [13]:
import numpy as np

Creating arrays (table)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [28]:
a = np.array([1,3,4,7,8])
a

array([1, 3, 4, 7, 8])

In [31]:
a[2] = 10

In [32]:
a

array([ 1,  3, 10,  7,  8])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [39]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

Multi-demational arrays

In [40]:
np.zeros([6,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
n = np.array([
    [1,2,3],
    [23,2,44]
])

In [57]:
n

array([[ 1,  2,  3],
       [23,  2, 44]])

In [58]:
n[1,2]

np.int64(44)